### PR TITLE
Fix print out to use dart prefix

### PR DESCRIPTION
**Pull request by kimlarson-wk**
Copy pasta is nice. Let's make things easy.

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by evanweible-wf — APPROVED** [review]

**Review by dustinlessard-wf — APPROVED** [review]

**Comment by dustinlessard-wf** [comment]
QA+1

@Workiva/release-management-p

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Comment by evanweible-wf** [comment]
@kimlarson-wk after the master merge, I don't think there are actually any changes in this PR. Should we close it?

**Pull request closed without merging**
